config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :customer_accounts
  resources :teams_users, only: [:index]
  resources :apidocs, only: [:index]
  resources :profiles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  namespace :api do
    namespace :v1 do
      resources :customer_accounts
      resources :users
      resources :profiles, only: :index
    end
  end
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  include Swagger::ProfileSchema

  has_and_belongs_to_many :permissions
  has_many :roles

  validates :name,
            presence: true,
            uniqueness: true

  scope :elegibles, -> (is_admin= false, names = ['SuperAdmin']) {
    names << 'Admin' unless is_admin
    where.not(name: names)
  }
end

app/controllers/api/v1/profiles_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ProfilesController < BaseController
      include Swagger::ProfilesApi

      after_action :verify_authorized, if: :current_user

      def index
        @profiles = policy_scope(Profile).all
        authorize @profiles
      end
    end
  end
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

class ProfilesController < ApplicationController
  after_action :verify_authorized, if: :current_user
  before_action :set_profile, only: %i[show edit update destroy]

  def index
    @profiles = Profile.all
    authorize @profiles
  end

  def show; end

  def new
    @profile = Profile.new
    authorize @profile
  end

  def edit;end

  def create
    @profile = Profile.new(profile_params)
    authorize @profile
    respond_to do |format|
      if @profile_params.save
        redirect_to profile_url(@profile), notice: 'Profile was successfully created.' 
      else
        render :new, status: :unprocessable_entity 
      end
    end
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        redirect_to profile_url(@profile), notice: 'Profile was successfully updated.'
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  private

  def set_profile
    @profile = policy_scope(Profile).find(params[:id])
    authorize @profile
  end

  def profile_params
    params.require(:profile).permit(:name, permission_ids: [])
  end
end

app/views/profiles/_form.html.erb
<div class="row">
  <div class="col-12 col-md-6">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="col-12 col-md-6">
    <div class="form-group">
      <%= f.label :permissions %>
      <%= f.select :permission_ids, Permission.all.collect { |x| [x.name, x.id]}, {:include_hidden =>false}, multiple: 'multiple', 'data-controller': 'select', class: 'form-control select2' %>
    </div>
  </div>  
</div>

app/views/profiles/edit.html.erb
<% content_for :page_title do %>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= icon('fa-solid', 'lock')%>
        <%= link_to t('profiles.list'), profiles_url%>
      </li>
      <li class="breadcrumb-item active">  <%= @profile.name.capitalize %> </li>
    </ol>
  </nav>
<% end %>


<div class="card mb-3">
  <div class="card-header">
    <h1 class="card-title mb-0 h5">
      <%= t('profiles.form_title') %>
    </h1>
  </div>

  <div class="card-body">
    <div>
      <%= render partial: 'shared/error_messages', locals: { target: @profile } %>
    </div>
    <div>
      <%= form_for [@profile], url: profile_url(@profile), method: :put do |f| %>
        <%= render partial: 'form', locals: { f: f } %>
        <div>
          <%= render partial: 'shared/edit_resource_links', locals: { f: f,collection_url: profiles_url, resource: @profile } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<% content_for :page_title do %>
  <nav>
    <ol class="breadcrumb admin">
      <li class="breadcrumb-item active">
      <%= icon('fa-solid', 'lock')%>
      <%= link_to t('profiles.list'), profiles_url%>
      </li>
    </ol>
  </nav>
<% end %>

<% if @profiles.any? %>
  <table class="table" id="listing_profiles">
    <thead>
      <tr>
        <th>
          <%= t('profile.name') %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @profiles.each do |profile|%>
        <tr id="<%= dom_id profile %>">
          <td><%=link_to profile.name, edit_profile_url(profile) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>