config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :customer_accounts
  resources :teams_users, only: [:index]
  resources :apidocs, only: [:index]
  resources :profiles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  namespace :api do
    namespace :v1 do
      resources :customer_accounts
      resources :users
      resources :profiles, only: :index
    end
  end
end

app/models/customer_account.rb
# frozen_string_literal: true

class CustomerAccount < ApplicationRecord
  include Swagger::CustomerAccountSchema
  has_one :team
  accepts_nested_attributes_for :team

  has_many :users, through: :team

  validates :name,
            presence: true,
            uniqueness: true
  validates_presence_of :manager, :customer

  before_save :at_least_one_user_team

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

  private

  def at_least_one_user_team
    return unless users.blank?

    errors.add :users, :at_least_one
  end
end

app/controllers/api/v1/customer_accounts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class CustomerAccountsController < BaseController
      include Swagger::CustomerAccountsApi

      after_action :verify_authorized, if: :current_user
      before_action :set_customer, only: %i[show edit update destroy]

      def index
        @customer_accounts = policy_scope(CustomerAccount).all
        authorize @customer_accounts
      end

      def show
        render :show, status: :ok, location: @customer_account
      end

      def create
        @customer_account = CustomerAccount.new(customer_account_params)
        authorize @customer_account

        if @customer_account.save
          render :show, status: :created, location: @customer_account
        else
          render json: @customer_account.errors, status: :unprocessable_entity
        end
      end

      def update
        if @customer_account.update(customer_account_params)
          render :show, status: :ok, location: @customer_account
        else
          render json: @customer_account.errors, status: :unprocessable_entity
        end
      end

      def destroy
        if @customer_account.destroy
          render json: { status: 'Customer Account was successfully destroyed.'}
        else
          render json: @customer_account.errors, status: :unprocessable_entity
        end
      end

      private

      def set_customer
        @customer_account = policy_scope(CustomerAccount).find(params[:id])
        authorize @customer_account
      end
    
      def customer_account_params
        params.require(:customer_account).permit(:name, :customer, :manager,
                                                 team_attributes: [:id, { team_users_attributes: [:id, :user_id, :start_date, :end_date, :_destroy] }])
      end
    end
  end
end

app/controllers/customer_accounts_controller.rb
# frozen_string_literal: true

class CustomerAccountsController < ApplicationController
  after_action :verify_authorized, if: :current_user
  before_action :set_customer, only: %i[show edit update destroy]

  def index
    @customer_accounts = policy_scope(CustomerAccount).all
    authorize @customer_accounts
  end

  def show; end

  def new
    @customer_account = CustomerAccount.new
    setup_new_team
    authorize @customer_account
  end

  def edit
    setup_new_team
  end

  def create
    @customer_account = CustomerAccount.new(customer_account_params)
    authorize @customer_account

    respond_to do |format|
      if @customer_account.save
        format.html { redirect_to customer_accounts_url, notice: 'Account was successfully created.' }
        format.json { render :edit, status: :created, location: @customer_account }
      else
        setup_new_team # user_ids doesnt render
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer_account.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @customer_account.update(customer_account_params)
        format.html { redirect_to customer_accounts_url, notice: 'Account was successfully updated.' }
        format.json { render :edit, status: :created, location: @customer_account }
      else
        setup_new_team # user_ids doesnt render
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer_account.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_customer
    @customer_account = policy_scope(CustomerAccount).find(params[:id])
    authorize @customer_account
  end

  def customer_account_params
    params.require(:customer_account).permit(:name, :customer, :manager,
                                             team_attributes: [:id, { team_users_attributes: [:id, :user_id, :start_date, :end_date, :_destroy] }])
  end

  def setup_new_team
    @customer_account.build_team if @customer_account.team.nil?
    @customer_account.team.team_users.build if @customer_account.team.team_users.empty?
  end
end

app/views/customer_accounts/_form.html.erb
<div class="row">
  <div class="col-12 col-md-6">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="col-12 col-md-6">
    <div class="form-group">
      <%= f.label :customer %>
      <%= f.text_field :customer, class: 'form-control' %>
    </div>
  </div>
  <div class="col-12 col-md-6">
    <div class="form-group">
      <%= f.label :manager %>
      <%= f.text_field :manager, class: 'form-control' %>
    </div>
  </div>

</div>

  <%= button_tag(type: 'button', class: 'add_fields btn btn-success', 'data-target': 'tbody#team_users', 'data-controller': 'fields') do %> 
   <%= icon('fa-solid', 'plus')%>
   <span> <%= t('add_user') %> </span>
  <%end%>

  <%= f.fields_for :team do |team_form| %>
    <%= team_form.hidden_field :id %>
    <table class="table">
      <tbody id="team_users">
        <%= team_form.fields_for :team_users do |team_user_form| %>
          <tr class="row">
            <%= team_user_form.hidden_field :id %>
            <td class="col-8 col-md-4">
              <div class="form-group">
                <%= team_user_form.label :user_id %>
                <%= team_user_form.select :user_id, 
                                    User.all.collect { |x| [x.email, x.id]}, 
                                    {include_blank: 'Select User'}, 'data-controller': 'select', class: 'form-control select2' %>
              </div>
            </td>
            <td class="col-8 col-md-4">
              <div class="form-group">
                <%= team_user_form.label :start_date %>
                <%= team_user_form.date_field :start_date, class: 'form-control' %>
              </div>
            </td>
            <td class="col-7 col-md-3">
              <div class="form-group">
                <%= team_user_form.label :end_date %>
                <%= team_user_form.date_field :end_date, class: 'form-control' %>
              </div>
            </td>
            <td class="col-1 col-md-1 d-sm-flex align-items-sm-center justify-content-sm-between">
              <%= team_user_form.hidden_field :_destroy, id: 'delete_member', 'data-controller': "deleteable" %>
              <%= icon('fa-solid', 'trash delete_member btn btn-danger')%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

app/views/customer_accounts/edit.html.erb
<% content_for :page_title do %>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= icon('fa-solid', 'building')%>
        <%= link_to t('customer_accounts.list'), customer_accounts_url%>
      </li>
      <li class="breadcrumb-item">
        <%= t('customer_accounts.edit') %>
      </li>
      <li class="breadcrumb-item active">
        <%=@customer_account.name %>
      </li>

    </ol>
  </nav>
<% end %>

<div class="card mb-3">
  <div class="card-header">
    <h1 class="card-title mb-0 h5">
      <%= t('customer_accounts.form_title') %>
    </h1>
  </div>

  <div class="card-body">
    <div>
      <%= render partial: 'shared/error_messages', locals: { target: @customer_account } %>
    </div>
    <div>
      <%= form_with(model: @customer_account) do |f| %>
        <%= render partial: 'form', locals: { f: f } %>
        <div>
          <%= render partial: 'shared/edit_resource_links', locals: { f: f, collection_url: customer_accounts_url, resource: CustomerAccount } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customer_accounts/index.html.erb
<% content_for :page_title do %>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item active">
      <%= icon('fa-solid', 'building')%>
      <%= link_to t('customer_accounts.list'), customer_accounts_path%>
      </li>
    </ol>
    <% content_for :page_actions do %>
      <%= link_to new_customer_account_path, class: "btn btn-success", id: 'new_customer_account_link' do %>
        <%= icon('fa-solid', 'plus')%>
        <span> <%= t('customer_account.new') %> </span>
      <% end %>
    <% end if policy(:customer_account).create? %>
  </nav>
<% end %>
<div id="customer_accounts_list">
  <table class="table">
    <thead>
      <th> Account Name</th>
      <th> Customer Name </th>
      <th> Operation Manager</th>
      <th> Team Users Size </th>
    </thead>
    <tbody>
      <% @customer_accounts.each do |account| %>
            <tr>
              <td> 
                <%= link_to account.name, edit_customer_account_path(account) %> 
              </td>
              <td> <%= account.customer %> </td>
              <td> <%= account.manager %> </td>
              <td> <%= account.users.try(:count) %> </td>
            </tr>

      <% end %>
    </tbody>
  </table>
</div>

app/views/customer_accounts/new.html.erb
<% content_for :page_title do %>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= icon('fa-solid', 'building')%>
        <%= link_to t('customer_accounts.list'), customer_accounts_url%>
      </li>
      <li class="breadcrumb-item active">
        <%= t('customer_accounts.new') %>
      </li>
    </ol>
  </nav>
<% end %>

<div class="card mb-3">
  <div class="card-header">
    <h1 class="card-title mb-0 h5">
      <%= t('customer_accounts.form_title') %>
    </h1>
  </div>

  <div class="card-body">
    <div>
      <%= render partial: 'shared/error_messages', locals: { target: @customer_account } %>
    </div>
    <div>
      <%= form_with(model: @customer_account) do |f| %>
        <%= render partial: 'form', locals: { f: f } %>
        <div>
          <%= render partial: 'shared/new_resource_links', locals: { f: f, collection_url: customer_accounts_url, resource: CustomerAccount } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customer_accounts/show.html.erb
<% content_for :page_title do %>
  <nav>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= icon('fa-solid', 'building')%>
        <%= link_to t('customer_accounts.list'), customer_accounts_url%>
      </li>
      <li class="breadcrumb-item">
        <%= t('customer_accounts.show') %>
      </li>
      <li class="breadcrumb-item active">
        <%=@customer_account.name %>
      </li>

    </ol>
  </nav>
<% end %>

<div class="card mb-3">
  <div class="card-header">
    <h1 class="card-title mb-0 h5">
      <%= t('customer_accounts.form_title') %>
    </h1>
  </div>

  <div class="card-body">
    <div>
    </div>
    <div>

    </div>
  </div>
</div>