config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :customer_accounts
  resources :teams_users, only: [:index]
  resources :apidocs, only: [:index]
  resources :profiles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  namespace :api do
    namespace :v1 do
      resources :customer_accounts
      resources :users
      resources :profiles, only: :index
    end
  end
end

app/controllers/teams_users_controller.rb
# frozen_string_literal: true

class TeamsUsersController < ApplicationController
  after_action :verify_authorized, if: :current_user
  def index
    @teams_users = policy_scope(TeamUser).unscoped.all
    authorize @teams_users

    @search = @teams_users.ransack(params[:q])
    @teams_users = @search.result(distinct: true)
  end
end

app/views/teams_users/_filter_table.html.erb
<% content_for :table_filter do %>
  <%= search_form_for @search, url: teams_users_path do |f| %>
      <div class="row">
        <div class="col-8 col-lg-4">
          <div class="form-group">
            <%= f.label :user_email_cont, t('searches.user_email') %>
            <%= f.text_field :user_email_cont, class: "form-control js-quick-search-target js-filterable" %>
          </div>
        </div>
        <div class="col-8 col-lg-4">
          <div class="form-group">
            <%= f.label :user_name_cont, t('searches.user_name') %>
            <%= f.text_field :user_name_cont, class: "form-control js-filterable" %>
          </div>
        </div>
        <div class="col-8 col-lg-4">
          <div class="form-group">
            <%= f.label :customer_account_name_cont, t('searches.customer_account_name') %>
            <%= f.text_field :customer_account_name_cont, class: "form-control js-filterable" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-lg-6">
          <div class="form-group">
            <%= f.label :start_date_eq, t('searches.team_users_start_date') %>
            <%= f.date_field :start_date_eq, class: "form-control js-filterable" %>
          </div>
        </div>
        <div class="col-12 col-lg-6">
          <div class="form-group">
            <%= f.label :end_date_eq, t('searches.team_users_end_date') %>
            <%= f.date_field :end_date_eq, class: "form-control js-filterable" %>
          </div>
        </div>
      </div>
      <div class="form-actions">
        <%= button_tag(t(:search), type: 'search', class: 'btn btn-success') %>
      </div>
  <% end  %>
<%end %>

app/views/teams_users/index.html.erb
<% content_for :page_title do %>
  <nav>
    <ol class="breadcrumb admin">
      <li class="breadcrumb-item active">
      <%= icon('fa-solid', 'briefcase')%>
      <%= link_to t('teams_users.list'), teams_users_path%>
      </li>
    </ol>
  </nav>
<% end %>

<%= render 'filter_table' %>
<div class="card mb-3">
  <div class="card-body">
    <table class="table">
      <thead>
        <th> User </th>
        <th> Account Name</th>
        <th> Stars At </th>
        <th> Ends At </th>
        <th> Dropped Out </th>
      </thead>
      <tbody>
        <% @teams_users.each do |team_user| %>
          <tr>
            <td><%=link_to team_user.email, user_path(team_user.user)%> </td>
            <td><%=team_user.name%> </td>
            <td><%=team_user.start_date.to_date%> </td>
            <td><%=team_user.end_date.to_date%> </td>
            <td><%=team_user.deleted_at.try(:to_date)%> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>